//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.30 at 08:49:48 AM BRT 
//
package br.ufg.inf.findbugsparser;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the br.ufg.inf.findbugsparser package.
 * <p>An ObjectFactory allows you to programatically construct new instances of
 * the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the
 * binding of schema type definitions, element declarations and model groups.
 * Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Message_QNAME = new QName("", "Message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: br.ufg.inf.findbugsparser
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance }
     *
     */
    public BugCollection.BugInstance createBugCollectionBugInstance() {
        return new BugCollection.BugInstance();
    }

    /**
     * Create an instance of {@link BugCollection.BugCategory }
     *
     */
    public BugCollection.BugCategory createBugCollectionBugCategory() {
        return new BugCollection.BugCategory();
    }

    /**
     * Create an instance of {@link BugCollection.FindBugsSummary }
     *
     */
    public BugCollection.FindBugsSummary createBugCollectionFindBugsSummary() {
        return new BugCollection.FindBugsSummary();
    }

    /**
     * Create an instance of {@link BugCollection.FindBugsSummary.FindBugsProfile
     * }
     *
     */
    public BugCollection.FindBugsSummary.FindBugsProfile createBugCollectionFindBugsSummaryFindBugsProfile() {
        return new BugCollection.FindBugsSummary.FindBugsProfile();
    }

    /**
     * Create an instance of {@link BugCollection.ClassFeatures.ClassFeatureSet.Feature
     * }
     *
     */
    public BugCollection.ClassFeatures.ClassFeatureSet.Feature createBugCollectionClassFeaturesClassFeatureSetFeature() {
        return new BugCollection.ClassFeatures.ClassFeatureSet.Feature();
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance.String }
     *
     */
    public BugCollection.BugInstance.String createBugCollectionBugInstanceString() {
        return new BugCollection.BugInstance.String();
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance.LocalVariable }
     *
     */
    public BugCollection.BugInstance.LocalVariable createBugCollectionBugInstanceLocalVariable() {
        return new BugCollection.BugInstance.LocalVariable();
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance.Field }
     *
     */
    public BugCollection.BugInstance.Field createBugCollectionBugInstanceField() {
        return new BugCollection.BugInstance.Field();
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance.Property }
     *
     */
    public BugCollection.BugInstance.Property createBugCollectionBugInstanceProperty() {
        return new BugCollection.BugInstance.Property();
    }

    /**
     * Create an instance of {@link BugCollection.ClassFeatures }
     *
     */
    public BugCollection.ClassFeatures createBugCollectionClassFeatures() {
        return new BugCollection.ClassFeatures();
    }

    /**
     * Create an instance of {@link BugCollection.FindBugsSummary.PackageStats }
     *
     */
    public BugCollection.FindBugsSummary.PackageStats createBugCollectionFindBugsSummaryPackageStats() {
        return new BugCollection.FindBugsSummary.PackageStats();
    }

    /**
     * Create an instance of {@link SourceLine }
     *
     */
    public SourceLine createSourceLine() {
        return new SourceLine();
    }

    /**
     * Create an instance of {@link BugCollection.FindBugsSummary.FindBugsProfile.ClassProfile
     * }
     *
     */
    public BugCollection.FindBugsSummary.FindBugsProfile.ClassProfile createBugCollectionFindBugsSummaryFindBugsProfileClassProfile() {
        return new BugCollection.FindBugsSummary.FindBugsProfile.ClassProfile();
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance.Class }
     *
     */
    public BugCollection.BugInstance.Class createBugCollectionBugInstanceClass() {
        return new BugCollection.BugInstance.Class();
    }

    /**
     * Create an instance of {@link BugCollection.FindBugsSummary.FileStats }
     *
     */
    public BugCollection.FindBugsSummary.FileStats createBugCollectionFindBugsSummaryFileStats() {
        return new BugCollection.FindBugsSummary.FileStats();
    }

    /**
     * Create an instance of {@link BugCollection.Project }
     *
     */
    public BugCollection.Project createBugCollectionProject() {
        return new BugCollection.Project();
    }

    /**
     * Create an instance of {@link BugCollection }
     *
     */
    public BugCollection createBugCollection() {
        return new BugCollection();
    }

    /**
     * Create an instance of {@link BugCollection.BugCode }
     *
     */
    public BugCollection.BugCode createBugCollectionBugCode() {
        return new BugCollection.BugCode();
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance.Method }
     *
     */
    public BugCollection.BugInstance.Method createBugCollectionBugInstanceMethod() {
        return new BugCollection.BugInstance.Method();
    }

    /**
     * Create an instance of {@link BugCollection.History }
     *
     */
    public BugCollection.History createBugCollectionHistory() {
        return new BugCollection.History();
    }

    /**
     * Create an instance of {@link BugCollection.Errors }
     *
     */
    public BugCollection.Errors createBugCollectionErrors() {
        return new BugCollection.Errors();
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance.Int }
     *
     */
    public BugCollection.BugInstance.Int createBugCollectionBugInstanceInt() {
        return new BugCollection.BugInstance.Int();
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance.UserAnnotation }
     *
     */
    public BugCollection.BugInstance.UserAnnotation createBugCollectionBugInstanceUserAnnotation() {
        return new BugCollection.BugInstance.UserAnnotation();
    }

    /**
     * Create an instance of {@link BugCollection.ClassFeatures.ClassFeatureSet
     * }
     *
     */
    public BugCollection.ClassFeatures.ClassFeatureSet createBugCollectionClassFeaturesClassFeatureSet() {
        return new BugCollection.ClassFeatures.ClassFeatureSet();
    }

    /**
     * Create an instance of {@link BugCollection.FindBugsSummary.PackageStats.ClassStats
     * }
     *
     */
    public BugCollection.FindBugsSummary.PackageStats.ClassStats createBugCollectionFindBugsSummaryPackageStatsClassStats() {
        return new BugCollection.FindBugsSummary.PackageStats.ClassStats();
    }

    /**
     * Create an instance of {@link BugCollection.History.AppVersion }
     *
     */
    public BugCollection.History.AppVersion createBugCollectionHistoryAppVersion() {
        return new BugCollection.History.AppVersion();
    }

    /**
     * Create an instance of {@link BugCollection.BugInstance.Type }
     *
     */
    public BugCollection.BugInstance.Type createBugCollectionBugInstanceType() {
        return new BugCollection.BugInstance.Type();
    }

    /**
     * Create an instance of {@link BugCollection.BugPattern }
     *
     */
    public BugCollection.BugPattern createBugCollectionBugPattern() {
        return new BugCollection.BugPattern();
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Message")
    public JAXBElement<java.lang.String> createMessage(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Message_QNAME, java.lang.String.class, null, value);
    }
}
