/*
 * Hammurapi
 * Automated Java code review system. 
 * Copyright (C) 2004  Hammurapi Group
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * URL: http://www.hammurapi.org
 * e-Mail: support@hammurapi.biz

*/
package org.hammurapi.inspectors.testcases.fixes;

import java.io.FileInputStream;
import java.io.InputStream;

import org.hammurapi.inspectors.testcases.HammurapiTestCasesException;

/**
 * CodeTooLongRule
 * @author  Pavel Vlasov
 * @version $Revision: 1.1 $
 */
public class CodeTooLongRuleFixTestCase {

	private static org.apache.log4j.Logger logger =
		org.apache.log4j.Logger.getRootLogger();

	private static final String FILE_ERROR_TXT = "File error";
	private static final String CASE_TXT1 = "case 1";
	private static final String CASE_TXT2 = "case 2";
	private static final String CASE_TXT3 = "case 3";
	private static final int CASE_NBR1 = 1;
	private static final int CASE_NBR2 = 2;
	private static final int CASE_NBR3 = 3;
	private static final int CASE_NBR4 = 4;

	// --- FIX ---
	/** Java doc automaticaly generated by Hammurapi */
	public int getByte(final String fName,  final String which)
		throws HammurapiTestCasesException {

		if (CASE_TXT1.compareTo(which)==0) {
			return getByte(fName, CASE_NBR1);
		} else if (CASE_TXT2.compareTo(which)==0) {
			return getByte(fName, CASE_NBR2);
		} else if (CASE_TXT3.compareTo(which)==0) {
			return getByte(fName, CASE_NBR3);
		} else {
			return getByte(fName, CASE_NBR4);
		}
	}
	
	/** Java doc automaticaly generated by Hammurapi */
	public int getByte(final String fName,  final int nbr)
		throws HammurapiTestCasesException {
			
		try {
			InputStream is = new FileInputStream(fName);
			int c = 0;
			int retVal = 0;
			while (c<nbr) {
				retVal = is.read();
			}
			return retVal;

		} catch (java.io.IOException e) {
			logger.fatal(FILE_ERROR_TXT, e);
			throw new HammurapiTestCasesException(e);
		}
	}
	// --- END FIX ---
	
}

