/*
 * Hammurapi
 * Automated Java code review system. 
 * Copyright (C) 2004  Hammurapi Group
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * URL: http://www.hammurapi.org
 * e-Mail: support@hammurapi.biz

*/
package org.hammurapi.inspectors.testcases.fixes;

import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;

import org.hammurapi.inspectors.testcases.HammurapiTestCasesException;

/**
 * EmptyCatchBlockRule
 * @author  Pavel Vlasov
 * @version $Revision: 1.1 $
 */
public class EmptyCatchBlockRuleFixTestCase {

	private static org.apache.log4j.Logger logger =
		org.apache.log4j.Logger.getRootLogger();

	private static final String FILE_ERROR_TXT = "File error";
	private static final String FILE_ERROR2_TXT = "File not found error";

	/** Java doc automaticaly generated by Hammurapi */
	public int getFirstByte(final String fName) 
		throws HammurapiTestCasesException {
			
		try {
			Reader r = new FileReader(fName);
			return r.read();

		} catch (java.io.FileNotFoundException e) {

			//    --- FIX ---
			logger.fatal(FILE_ERROR2_TXT, e);
			throw new HammurapiTestCasesException(e);

		} catch (IOException e) {
			logger.fatal(FILE_ERROR_TXT, e);
			throw new HammurapiTestCasesException(e);
		}
	}
}

