/*
 * Hammurapi
 * Automated Java code review system. 
 * Copyright (C) 2004  Hammurapi Group
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * URL: http://www.hammurapi.org
 * e-Mail: support@hammurapi.biz

*/

// --- FIX ---
package org.hammurapi.inspectors.testcases.fixes;

import java.io.FileInputStream;
import java.io.InputStream;

import org.hammurapi.inspectors.testcases.HammurapiTestCasesException;

/**
 * MaxLinesInFileRule
 * @author  Pavel Vlasov
 * @version $Revision: 1.1 $
 */
public class MaxLinesInFileRuleFixTestCase {

	private static org.apache.log4j.Logger logger =
		org.apache.log4j.Logger.getRootLogger();

	private static final String FILE_ERROR_TXT = "File error";
	private static final int POS_1 = 1;
	private static final int POS_2 = 2;
	private static final int POS_3 = 3;
	private static final int POS_4 = 4;

	/** Java doc automaticaly generated by Hammurapi */
	public int getFirstByte(final String fName)
		throws HammurapiTestCasesException {
			
		return getByte(fName, POS_1);		
	}

	/** Java doc automaticaly generated by Hammurapi */
	public int getSecondByte(final String fName)
		throws HammurapiTestCasesException {
	
		return getByte(fName, POS_2);		
	}

	/** Java doc automaticaly generated by Hammurapi */
	public int getThirdByte(final String fName)
		throws HammurapiTestCasesException {
	
		return getByte(fName, POS_2);		
	}

	/** Java doc automaticaly generated by Hammurapi */
	public int getFourthByte(final String fName)
		throws HammurapiTestCasesException {
	
		return getByte(fName, POS_2);		
	}

	private int getByte(final String fName, final int pos)
		throws HammurapiTestCasesException {
			
		try {
			InputStream is = new FileInputStream(fName);
			int retVal = 0;
			int i = 0;
			while (i<pos) {
				retVal = is.read();
			}
			return retVal;

		} catch (Exception e) {
			logger.fatal(FILE_ERROR_TXT, e);
			throw new HammurapiTestCasesException(e);
		}
	}
}
// --- END FIX ---

