/*
 * Hammurapi
 * Automated Java code review system. 
 * Copyright (C) 2004  Hammurapi Group
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * URL: http://www.hammurapi.org
 * e-Mail: support@hammurapi.biz

*/
package org.hammurapi.inspectors.testcases.fixes;

/**
 * NamingStandardRule
 * @author  Pavel Vlasov
 * @version $Revision: 1.1 $
 */
public class NamingStandardRuleFixTestCase {

	private static org.apache.log4j.Logger logger =
		org.apache.log4j.Logger.getRootLogger();

	private class InnerClass1 {

		//  --- FIX ---
		private static final int ATTRFIRST = INT_12;

		boolean attrBoolean;
	}

	//--- FIX ---
	private class InnerClass2 {
		private static final int ATTRFIRST = INT_12;
		boolean attrBoolean;
	}

	//--- FIX ---
	private class InnerClass {

		//  --- FIX ---
		private static final int ATTRFIRST = INT_12;

		boolean attrBoolean;
	}

	private static final int INT_12 = 12;
	private static final String ANATTRIBUTE = "ASDF";
	public final String /** Java doc automaticaly generated by Hammurapi */
	anAttribute = ANATTRIBUTE;
	protected java.util.Date /** Java doc automaticaly generated by Hammurapi */
	fromDate;

	//--- FIX ---
	private static final String ANATTRIBUTE2 = ANATTRIBUTE;

	// --- FIX ---
	public final String /** Java doc automaticaly generated by Hammurapi */
	anAttribute2 = ANATTRIBUTE;

	// --- FIX ---
	protected java.util.Date /** Java doc automaticaly generated by Hammurapi */
	fromDate2;

	void method1() {
	}

	//--- FIX ---
	void method2() {
	}

	private static String methodToCall(final Integer parOne, 
		final String parTwo) {

		//  --- FIX ---
		String s = ANATTRIBUTE;

		return s;
	}

	//--- FIX ---
	private static String methodToCall(final Long parOne) {
		String s = ANATTRIBUTE;
		return s;
	}

	//--- FIX ---
	private static String methodToCall(final Long parOne, 
		final String parTwo) {
			
		String s = ANATTRIBUTE;
		return s;
	}
}

