/*
 * Hammurapi
 * Automated Java code review system. 
 * Copyright (C) 2004  Hammurapi Group
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * URL: http://www.hammurapi.org
 * e-Mail: support@hammurapi.biz

*/
package org.hammurapi.inspectors.testcases.violations;

/**
 * NamingStandardRule
 * @author  Pavel Vlasov
 * @version $Revision: 1.1 $
 */
public class NamingStandardRuleViolationTestCase {

	private static org.apache.log4j.Logger logger =
		org.apache.log4j.Logger.getRootLogger();

	private class InnerClass1 {

		//  --- VIOLATION ---
		private static final int attrFirst = INT_12;

		boolean attrBoolean;
	}

	//--- VIOLATION ---
	private class innerClass2 {
		private static final int ATTRFIRST = INT_12;
		boolean attrBoolean;
	}

	//--- VIOLATION ---
	private class Inner_Class {

		//  --- VIOLATION ---
		private static final int attrFirst = INT_12;

		boolean attrBoolean;
	}

	private static final int INT_12 = 12;
	private static final String ANATTRIBUTE = "ASDF";
	public final String /** Java doc automaticaly generated by Hammurapi */
	anAttribute = ANATTRIBUTE;
	protected java.util.Date /** Java doc automaticaly generated by Hammurapi */
	fromDate;

	//--- VIOLATION ---
	private static final String ANAtTRIBUTE2 = ANATTRIBUTE;

	// --- VIOLATION ---
	public final String /** Java doc automaticaly generated by Hammurapi */
	AnAttribute2 = ANATTRIBUTE;

	// --- VIOLATION ---
	protected java.util.Date /** Java doc automaticaly generated by Hammurapi */
	from_Date2;

	void method1() {
	}

	//--- VIOLATION ---
	void Method2() {
	}

	private static String methodToCall(final Integer parOne, 
		final String parTwo) {

		//  --- VIOLATION ---
		String S = ANATTRIBUTE;

		return S;
	}

	//--- VIOLATION ---
	private static String methodToCall(final Long ParOne) {
		String s = ANATTRIBUTE;
		return s;
	}

	//--- VIOLATION ---
	private static String methodToC_all(final Long parOne, 
		final String par_Two) {
			
		String s = ANATTRIBUTE;
		return s;
	}
}

